#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# set displays for each monitor
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

# basic config
bspc config border_width 3
bspc config window_gap 24
bspc config split_ratio 0.50
